use Mix.Config

# Configure your database
config :loanmanagementsystem, Loanmanagementsystem.Repo,
<<<<<<< HEAD
  database: "paykesho_uat",
  hostname: "localhost",
  username: "probase",
  password: "Password123$$",
=======

  database: "pangea_loans_prod_v4",
  hostname: "localhost",
  username: "postgres",
  # username: "probase",
  # password: "incorrect",
  # password: "Password123$$",
  # password: "chanda999@",
  password: "qwerty12",
  # password: "Pangea@$123",

>>>>>>> a19059c1270cd87ec0924a2c61fa4b5a8b6f6518
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :loanmanagementsystem, LoanmanagementsystemWeb.Endpoint,
  http: [port: 5050],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# config :loanmanagementsystem, LoanmanagementsystemWeb.Endpoint,
# 	force_ssl: [hsts: true],
#     url: [host: "www.pangaeaaddcapital.finance", port: 443],
#     http: [port: 5000],
#     https: [
#       port: 443,
#       protocol_options: [
#         idle_timeout: 245_000
#       ],
#       cipher_suite: :strong,
#       certfile: "/etc/letsencrypt/live/pangaeaaddcapital.finance/fullchain.pem",
#       keyfile: "/etc/letsencrypt/live/pangaeaaddcapital.finance/privkey.pem"
#     ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :loanmanagementsystem, LoanmanagementsystemWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/loanmanagementsystem_web/(live|views)/.*(ex)$",
      ~r"lib/loanmanagementsystem_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
